---

# Setup
title:               Ionic.Zone
tagline:             'A site about Ionic Framework'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://ionic.zone
baseurl:             ''
paginate:            5
timezone:            UTC
permalink:           pretty
markdown:            kramdown
highlighter:         rouge

# About/contact
author:
  name:              Jan Piotrowski
  url:               https://janpiotrowski.de
  email:             ionicdotzone@gmail.com


# Collections
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  articles:
    output: true
    permalink: /:path

# Defaults
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article

# Custom vars
version:             1.0.0
