---

# Setup
title:               ionic.zone
tagline:             'a site about all things Ionic (Staging)'
description:         ''
url:                 https://staging.ionic.zone
baseurl:             ''
paginate:            5
timezone:            UTC
permalink:           /:path
highlighter:         rouge
markdown:            kramdown
kramdown:
  parse_block_html: true


# About/contact
author:
  name:              Jan Piotrowski
  url:               https://janpiotrowski.de
  email:             ionicdotzone@gmail.com
github:
  repo:              https://github.com/janpio/ionic.zone

# Collections
collections:
  articles:
    title: Articles
    output: true
    permalink: /:path

# Defaults
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article

# Custom vars
version:             0.0.1
analytics_id:        UA-106337676-2

# Gems configuration
relative_links:
  enabled: true
  collections: true

plugins:
  - jekyll-relative-links
