---
title: Ionic.Zone
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  articles:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
markdown: kramdown
highlighter: rouge
permalink: pretty
tagline: A Jekyll theme
description: A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a>
  theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo"
  target="_blank">@mdo</a>.
url: http://ionic.zone
baseurl: 
author:
  name: Mark Otto
  url: https://twitter.com/mdo
paginate: 5
version: 2.1.0
github:
  repo: https://github.com/poole/hyde
